/**
 * Country → capital coordinates for map event placement.
 * Static, no API. Used when event country is known.
 */
export const CAPITAL_COORDS: Record<string, [number, number]> = {
  US: [38.9072, -77.0369],
  CA: [45.4215, -75.6972],
  UK: [51.5074, -0.1278],
  DE: [52.52, 13.405],
  FR: [48.8566, 2.3522],
  IT: [41.9028, 12.4964],
  ES: [40.4168, -3.7038],
  NL: [52.3676, 4.9041],
  CH: [46.948, 7.4474],
  CN: [39.9042, 116.4074],
  JP: [35.6762, 139.6503],
  KR: [37.5665, 126.978],
  TW: [25.033, 121.5654],
  IN: [28.6139, 77.209],
  HK: [22.3193, 114.1694],
  SG: [1.3521, 103.8198],
  SA: [24.7136, 46.6753],
  UA: [50.4501, 30.5234],
  IR: [35.6892, 51.389],
  IL: [31.7683, 35.2137],
  RU: [55.7558, 37.6173]
};

export const FALLBACK_COORD: [number, number] = [50.8503, 4.3517];

/**
 * Map event titles to country for geo placement.
 * Extend as new events appear in API responses.
 */
export const EVENT_COUNTRY_MAP: Record<string, string> = {
  "Fed expected to hold rates steady": "US",
  "ECB expected to hold, data-dependent": "DE",
  "UK inflation expected to ease": "UK",
  "China property stabilization expected": "CN",
  "OPEC+ expected to extend cuts": "SA",
  "BOJ expected to keep ultra-loose": "JP",
  "Supply chain easing expected": "CN",
  "Ukraine talks may stall": "UA",
  "US-China EV tariff tensions may rise": "US",
  "European energy prices may spike": "DE",
  "US jobs report expected 180k gains": "US",
  "Fed pivot expectations may grow": "US",
  "Eurozone recession fears may mount": "DE",
  "Taiwan semi exports expected record": "TW",
  "Korean fab disruption risk": "KR",
  "EU AI regulation expected to pass": "DE",
  "Fed hike expected in March": "US",
  "Taiwan Strait tensions may escalate": "TW",
  "ECB expected to raise 25bps": "DE",
  "UK inflation may exceed expectations": "UK",
  "China property stress may spread": "CN",
  "OPEC+ may consider deeper cut": "SA",
  "Ukraine conflict may escalate": "UA",
  "US-China trade tensions may worsen": "US",
  "Japan BOJ policy shift hints": "JP",
  "European energy crisis may deepen": "DE",
  "US jobs data may surprise": "US",
  "Supply chain disruption risk at ports": "CN",
  "Fed pivot expectations may be dashed": "US",
  "Eurozone recession fears may grow": "DE",
  "Taiwan Strait carrier deployment risk": "TW",
  "US-China new tariffs expected": "US",
  "BOJ first rate hike expected": "JP",
  "OPEC+ Saudi may cut 1M bpd": "SA",
  "Samsung fab fire risk": "KR",
  "EU AI regulation fines expected": "DE",
  "Taiwan arms sale approval expected": "TW",
  "Fed speakers may hint at March hike": "US",
  "China Jan PMI preview may disappoint": "CN",
  "Germany factory orders may disappoint": "DE",
  "China Evergrande hearing may roil markets": "CN",
  "US Q4 GDP advance may beat expectations": "US",
  "Fed FOMC Jan meeting may signal March hike": "US",
  "Saudi Aramco Feb OSP may surprise": "SA",
  "Iran oil sanctions enforcement may tighten": "IR",
  "China Lunar New Year data may disappoint": "CN",
  "US Jan CPI may show sticky inflation": "US",
  "BoE may hold as services inflation persists": "UK",
  "US Congress Ukraine aid vote may delay": "UA",
  "Big Tech antitrust rulings may be announced": "US",
  "BOJ Shunto wage talks may exceed 4% target": "JP",
  "China Nvidia chip ban may extend further": "CN",
  "OPEC+ Feb meeting may extend voluntary cuts": "SA",
  "Eurozone Q4 GDP flash may confirm recession": "DE",
  "US-China chip rules may broaden to memory": "US",
  "US Jan retail sales may beat expectations": "US",
  "Samsung HBM ramp may face delays": "KR",
  "Gaza ceasefire talks may stall pre-Ramadan": "IL",
  "UK Spring Budget may signal pre-election spend": "UK",
  "China Two Sessions may announce stimulus": "CN",
  "OPEC+ JMMC may preview Q2 production policy": "SA",
  "Ukraine grain corridor renewal in doubt": "UA",
  "ECB March meeting may delay first rate cut": "DE",
  "US Feb NFP may show labor resilience": "US",
  "Taiwan new govt policy stance may clarify": "TW",
  "China rare earth quotas may be reduced": "CN",
  "BOJ March meeting may end negative rates": "JP",
  "EU DMA compliance deadlines may hit Big Tech": "DE",
  "France pension strikes may hit transport": "FR",
  "India EV subsidy cuts may be announced": "IN",
  "Swiss banking rules may tighten for UBS": "CH",
  "Italy deficit may breach EU limits": "IT",
  "China solar panel glut may worsen": "CN",
  "Dutch election may sway eurozone policy": "NL",
  "TSMC CoWoS capacity may stay tight": "TW",
  "Canada jobs data may show cooling": "CA",
  "Spain Catalonia tensions may resurface": "ES",
  "Banque de France may cut growth forecast": "FR",
  "Hong Kong property may extend slump": "HK",
  "Iran uranium enrichment may escalate": "IR",
  "SEC crypto rules may tighten further": "US",
  "Germany Ifo survey may show rebound": "DE",
  "Singapore wealth rules may tighten": "SG",
  "RBI may hold rates amid inflation": "IN",
  "France nuclear output may stay low": "FR",
  "Ukraine energy grid attacks may rise": "UA",
  "US Feb CPI may confirm sticky inflation": "US",
  "Korean battery output may lag demand": "KR",
  "China South China Sea drills may escalate": "CN",
  "Italy PMI may show manufacturing slump": "IT",
  "Russia sanctions may expand to metals": "RU",
  // Legacy / fixture fallbacks
  "Fed signals 50bps rate hike": "US",
  "Escalating tensions in Taiwan Strait": "TW",
  "ECB raises rates by 25bps": "DE",
  "UK inflation exceeds expectations": "UK",
  "China property sector stress": "CN",
  "OPEC+ production cut": "SA",
  "Russia-Ukraine conflict escalation": "UA",
  "US-China trade tensions": "US",
  "Japan BOJ policy shift": "JP",
  "European energy crisis": "DE",
  "US labor market data surprise": "US",
  "Global supply chain disruption": "CN",
  "Fed pivot expectations": "US",
  "Eurozone recession fears": "DE",
  "Taiwan semiconductor risk": "TW",
  "Semiconductor supply chain disruption": "KR",
  "EU passes AI regulation package": "DE"
};

export type Region = "US" | "Europe" | "Asia" | "Other";

const COUNTRY_REGION: Record<string, Region> = {
  US: "US",
  CA: "US",
  UK: "Europe",
  DE: "Europe",
  FR: "Europe",
  IT: "Europe",
  ES: "Europe",
  NL: "Europe",
  CH: "Europe",
  CN: "Asia",
  JP: "Asia",
  KR: "Asia",
  TW: "Asia",
  UA: "Europe",
  IR: "Asia",
  IL: "Other",
  RU: "Europe",
  IN: "Asia",
  HK: "Asia",
  SG: "Asia"
};

export function getRegion(country: string): Region {
  return COUNTRY_REGION[country] ?? "Other";
}
