import { useMemo } from "react";
import { useAppShellContext } from "../layout/AppShell";

export default function GeoRiskMapView() {
  const { response } = useAppShellContext();

  const hasOptionalMapData = useMemo(() => {
    if (!response) {
      return false;
    }
    const knownKeys = new Set(["portfolio", "timezone", "overnight_events"]);
    const responseRecord = response as unknown as Record<string, unknown>;
    return Object.keys(responseRecord).some((key) => !knownKeys.has(key));
  }, [response]);

  return (
    <section className="space-y-3">
      {!hasOptionalMapData ? (
        <article className="rounded-xl border border-dashed border-zinc-700 bg-zinc-900/40 p-8">
          <p className="text-sm font-medium text-zinc-200">
            Geo Risk Map is generated by backend/Supabase and will appear here when available.
          </p>
          <div className="mt-4 grid gap-3 sm:grid-cols-3">
            <div className="rounded-lg border border-zinc-800/70 bg-zinc-900/50 p-3 text-xs text-zinc-500">
              Americas
            </div>
            <div className="rounded-lg border border-zinc-800/70 bg-zinc-900/50 p-3 text-xs text-zinc-500">
              Europe
            </div>
            <div className="rounded-lg border border-zinc-800/70 bg-zinc-900/50 p-3 text-xs text-zinc-500">
              Asia
            </div>
          </div>
        </article>
      ) : response ? (
        <article className="rounded-xl border border-zinc-800/60 bg-zinc-900/40 p-4 text-sm text-zinc-300">
          Optional map payload detected in response. Frontend placeholder is active.
        </article>
      ) : null}
    </section>
  );
}
